ARG PHP_VERSION=7.4

FROM aprimediet/php:${PHP_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# INSTALL nginx
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update php7-pdo php7-mysqli php7-mysqlnd \
    php7-pdo_mysql

# Clean APK Cache
RUN rm -rf /var/cache/apk/*

EXPOSE 80