ARG PHP_VERSION=8

FROM aprimediet/php:${PHP_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# INSTALL nginx
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update php8-pdo php8-mysqli php8-mysqlnd \
    php8-pdo_mysql

# Clean APK Cache
RUN rm -rf /var/cache/apk/*

EXPOSE 80