ARG PHP_VERSION=8.1

FROM aprimediet/php:${PHP_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# INSTALL nginx
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update php81-pdo php81-mysqli php81-mysqlnd \
    php81-pdo_mysql

# Clean APK Cache
RUN rm -rf /var/cache/apk/*

EXPOSE 80