ARG PHP_VERSION=8.2

FROM aprimediet/php:${PHP_VERSION}
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# INSTALL nginx
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update php82-pdo php82-mysqli php82-mysqlnd \
    php82-pdo_mysql

# Clean APK Cache
RUN rm -rf /var/cache/apk/*

EXPOSE 80