ARG PHP_VERSION=5.6

FROM aprimediet/nginx-php:5.6
LABEL maintainer="<Muhamad Aditya Prima> aprimediet@gmail.com"

# INSTALL nginx
RUN --mount=type=cache,target=/var/cache/apk \
    apk add --update php5-pdo php5-mysqli php5-pdo_mysql

# Clean APK Cache
RUN rm -rf /var/cache/apk/*

EXPOSE 80